<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="MyiTestDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=myitest.mssql.somee.com;Persist Security Info=True;User ID=itestdata" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.iUserPermission" Member="iUserPermissions">
    <Type Name="iUserPermission">
      <Column Name="iUserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iFuncID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iPermission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="iFunction_iUserPermission" Member="iFunction" ThisKey="iFuncID" OtherKey="iFuncID" Type="iFunction" IsForeignKey="true" />
      <Association Name="iUser_iUserPermission" Member="iUser" ThisKey="iUserID" OtherKey="iUserID" Type="iUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.iFunction" Member="iFunctions">
    <Type Name="iFunction">
      <Column Name="iFuncID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iFuncName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="iFunction_iUserPermission" Member="iUserPermissions" ThisKey="iFuncID" OtherKey="iFuncID" Type="iUserPermission" />
    </Type>
  </Table>
  <Table Name="dbo.iUser" Member="iUsers">
    <Type Name="iUser">
      <Column Name="iUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iUserName" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="iPass" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="iEmailUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="iUser_iUserPermission" Member="iUserPermissions" ThisKey="iUserID" OtherKey="iUserID" Type="iUserPermission" />
      <Association Name="iUser_iSecurityQuest" Member="iSecurityQuests" ThisKey="iUserID" OtherKey="iSUserID" Type="iSecurityQuest" />
    </Type>
  </Table>
  <Table Name="dbo.iSubject" Member="iSubjects">
    <Type Name="iSubject">
      <Column Name="iSubjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iSubjectName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="iSubject_iChapter" Member="iChapters" ThisKey="iSubjectID" OtherKey="iSubjectID" Type="iChapter" />
    </Type>
  </Table>
  <Table Name="dbo.iChapter" Member="iChapters">
    <Type Name="iChapter">
      <Column Name="iChapID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iChapterNum" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="iChapterName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="iSubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="iChapter_iQuestion" Member="iQuestions" ThisKey="iChapID" OtherKey="iChapID" Type="iQuestion" />
      <Association Name="iSubject_iChapter" Member="iSubject" ThisKey="iSubjectID" OtherKey="iSubjectID" Type="iSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.iQuestion" Member="iQuestions">
    <Type Name="iQuestion">
      <Column Name="iQuestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="iChapID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="iBodyQuest" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="iImageQName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="iQuestion_iAnswer" Member="iAnswers" ThisKey="iQuestID" OtherKey="iQuestID" Type="iAnswer" />
      <Association Name="iChapter_iQuestion" Member="iChapter" ThisKey="iChapID" OtherKey="iChapID" Type="iChapter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.iAnswer" Member="iAnswers">
    <Type Name="iAnswer">
      <Column Name="iAnsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="iQuestID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iProperty" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="iBodyAns" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="iQuestion_iAnswer" Member="iQuestion" ThisKey="iQuestID" OtherKey="iQuestID" Type="iQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.iSecurityQuest" Member="iSecurityQuests">
    <Type Name="iSecurityQuest">
      <Column Name="iSID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="iSQuest" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="iSAns" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="iSUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="iUser_iSecurityQuest" Member="iUser" ThisKey="iSUserID" OtherKey="iUserID" Type="iUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.st_ChangePassword" Method="st_ChangePassword">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="newpassword" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_Check_AllSub_Type_Num" Method="st_Check_AllSub_Type_Num">
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="num" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_Check_aSub_aType_Num" Method="st_Check_aSub_aType_Num">
    <Parameter Name="sub" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="num" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAdmin" Method="st_CheckAdmin">
    <Parameter Name="iduser" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAvailableEmail" Method="st_CheckAvailableEmail">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAvailablePermission" Method="st_CheckAvailablePermission">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="func" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAvailableSubID" Method="st_CheckAvailableSubID">
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAvailableSubName" Method="st_CheckAvailableSubName">
    <Parameter Name="subname" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckAvailableUser" Method="st_CheckAvailableUser">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckChapIndex" Method="st_CheckChapIndex">
    <Parameter Name="chapnum" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckChapName" Method="st_CheckChapName">
    <Parameter Name="chapname" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CheckPermission" Method="st_CheckPermission">
    <Parameter Name="iduser" Type="System.Int32" DbType="Int" />
    <Parameter Name="FuncName" Parameter="funcName" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_CountQuestofSub" Method="st_CountQuestofSub">
    <Parameter Name="sub" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_DelQuest" Method="st_DelQuest">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_DelUser" Method="st_DelUser">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_DelUserFunction" Method="st_DelUserFunction">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="func" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_GetImageByID" Method="st_GetImageByID" IsComposable="true">
    <Parameter Name="img_pk" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.st_LoadAnsID" Method="st_LoadAnsID">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <Parameter Name="bodyans" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadBodyQuestOfSub" Method="st_LoadBodyQuestOfSub">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_LoadBodyQuestOfSubResult">
      <Column Name="[Body of Question]" Member="Body_of_Question" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_LoadChapID" Method="st_LoadChapID">
    <Parameter Name="chapname" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadChapName" Method="st_LoadChapName">
    <Parameter Name="chapid" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_LoadChapNameResult">
      <Column Name="iChapterName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_LoadCorrectAnswer" Method="st_LoadCorrectAnswer">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <Parameter Name="ansbody" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadFuncID" Method="st_LoadFuncID">
    <Parameter Name="func" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadOneAnsIDCorrect" Method="st_LoadOneAnsIDCorrect">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadQuestID" Method="st_LoadQuestID">
    <Parameter Name="body" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadSubjectID" Method="st_LoadSubjectID">
    <Parameter Name="subname" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_LoadUserID" Method="st_LoadUserID">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_Login" Method="st_Login">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_RandomIDofSub" Method="st_RandomIDofSub">
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_ResetPass" Method="st_ResetPass">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="mail" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="newpass" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_SelectAllChapter" Method="st_SelectAllChapter" IsComposable="true">
    <Parameter Name="idSub" Type="System.Int32" DbType="Int" />
    <Parameter Name="level" Type="System.String" DbType="Char(10)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.st_SelectAllLevel" Method="st_SelectAllLevel" IsComposable="true">
    <Parameter Name="idSub" Type="System.Int32" DbType="Int" />
    <Parameter Name="chapter" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.st_SelectAllQuest" Method="st_SelectAllQuest">
    <Parameter Name="idSub" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_SelectAllQuestResult">
      <Column Name="Questions" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Index]" Member="Chapter_Index" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Name]" Member="Chapter_Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_Test" Method="st_Test">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <Parameter Name="bodyans" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_SelectAllLevel" Method="st_SelectAllLevel1" IsComposable="true">
    <Parameter Name="idSub" Type="System.Int32" DbType="Int" />
    <Parameter Name="chapter" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.st_ViewQuestOfAllSub" Method="st_ViewQuestOfAllSub">
    <ElementType Name="st_ViewQuestOfAllSubResult">
      <Column Name="Questions" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Subject Name]" Member="Subject_Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Index]" Member="Chapter_Index" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Name]" Member="Chapter_Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_SelectQuest" Method="st_SelectQuest">
    <Parameter Name="idSub" Type="System.Int32" DbType="Int" />
    <Parameter Name="level" Type="System.String" DbType="Char(10)" />
    <Parameter Name="chapter" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_SelectQuestResult">
      <Column Name="Questions" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Number]" Member="Chapter_Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Chapter Name]" Member="Chapter_Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_Check_AllSub_aLevel_Num" Method="st_Check_AllSub_aLevel_Num">
    <Parameter Name="level" Type="System.Int32" DbType="Int" />
    <Parameter Name="num" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_Check_aSub_aLevel_Num" Method="st_Check_aSub_aLevel_Num">
    <Parameter Name="sub" Type="System.Int32" DbType="Int" />
    <Parameter Name="level" Type="System.Int32" DbType="Int" />
    <Parameter Name="num" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_RandomIDofSubByLevel" Method="st_RandomIDofSubByLevel">
    <Parameter Name="subid" Type="System.Int32" DbType="Int" />
    <Parameter Name="level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_GetUserInfo" Method="st_GetUserInfo">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_GetUserInfoResult">
      <Column Name="iUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="iUserName" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="iPass" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="iEmailUser" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_LoadImageName" Method="st_LoadImageName">
    <Parameter Name="idquest" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.st_getImageQuest" Method="st_getImageQuest">
    <Parameter Name="idquest" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_getImageQuestResult">
      <Column Name="iImageQName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.st_LoadBodyAnswers" Method="st_LoadBodyAnswers">
    <Parameter Name="questid" Type="System.Int32" DbType="Int" />
    <ElementType Name="st_LoadBodyAnswersResult">
      <Column Name="iBodyAns" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>